[workspace]
resolver = "3"
members = ["rattymedia-app", "rattymedia-embedded", "rattymedia-native", "rattymedia-server", ]

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
rattymedia-app = { path = "rattymedia-app" }
ratatui = { version = "0.30", default-features = false, features = ["all-widgets", "macros"] }
ratatui-core = { version = "0.1.2", features = [], default-features = false }

